
export const i18nDict = {
    "LPSM 2DID掃描系統": { vn: "Hệ thống scan quét mã LPSM 2DID" },
    "工號": { vn: "Mã số NV" },
    "姓名": { vn: "Họ tên" },
    "工單": { vn: "Công đơn" },
    "品目": { vn: "Mục hàng" },
    "總張數": { vn: "Tổng số trang" },
    "投入張數": { vn: "Số trang đầu vào" },
    "切換模式": { vn: "Thay đổi hình thức" },
    "上台面": { vn: "Mặt trên máy" },
    "下台面": { vn: "Mặt dưới máy" },
    "作業區": { vn: "Chỗ làm việc" },
    "放料區": { vn: "Chỗ để liệu" },
    "待入料": { vn: "Chờ nhập liệu" },
    "準備區-左": { vn: "Chỗ chuẩn bị -Trái" },
    "準備區-右": { vn: "Chỗ chuẩn bị -Phải" },
    "等待掃描...": { vn: "Chờ đợi scan..." },
    "原因": { vn: "Nguyên nhân" },
    "請刷入工號與工單以開始作業": { vn: "Hãy quẹt thẻ NV và công đơn để bắt đầu làm" },
    "換人生產": { vn: "Thay người làm sx" },
    "重整": { vn: "Chỉnh lại" },
    "強制執行": { vn: "Bắt buộc thực hiện" },
    "完成": { vn: "Hoàn thành" },
    "取消": { vn: "Hủy bỏ" },
    "確定": { vn: "Xác nhận" },
    "進": { vn: "Vào" },
    "出": { vn: "Ra" },
    "條碼異常": { vn: "Mã vạch bất thường" },
    "跳站": { vn: "Nhảy trạm " },
    "重工": { vn: "Làm lại" },
    "混工單;": { vn: "Lẫn công đơn" },
    "混品目;": { vn: "Lẫn mục hàng" },
    "混工單;混品目;": { vn: "Lẫn công đơn & Lẫn mục hàng" },
    "異常錯誤": { vn: "Sai lỗi bất thường" },
    "查無工單": { vn: "Ktra không có công đơn" },
    "查無品目": { vn: "Ktra không có mục hàng" },
    "超過 PANEL 上限": { vn: "Vượt quá PANEL giới hạn" },
    "工號驗證失敗": { vn: "Số thể nghiệm chứng thất bại" },
    "工號驗證時發生網路錯誤：請確認網路連線": { vn: "Khi nghiệm chứng số thẻ  NV mạng bị lỗi: Hãy kiểm tra lại mạng kết nối" },
    "工單驗證失敗：查無資料": { vn: "Nghiệm chứng công đơn thất bại: Không có tư liệu" },
    "工單驗證時發生網路錯誤，請確認網路連線": { vn: "Khi nghiệm chứng công đơn mạng bị lỗi: Hãy kiểm tra lại mạng kết nối" },
    "MES系統無該製品資訊": { vn: "Hệ thống MES không có thông tin sản phẩm này" },
    "此2DID之工單查無任何資料，因此不上傳資訊": { vn: "Công đơn 2DID này không có thông tin, do đó không thể đăng tải thông tin" },
    "驗證2DID發生錯誤，請確認網路連線": { vn: "Nghiệm chứng 2DID bị lỗi, hãy kiểm tra mạng kết nối" },
    "工單格式不正確，請重新掃描。": { vn: "Cách thức công đơn không đúng, hãy quét lại" },
    "產品條碼長度不正確，請重新掃描。": { vn: "Độ dài mã vạch sản phẩm không đúng, hãy quét lại" },
    "已達 PANEL 數上限，因此無法綁定。": { vn: "Đã đạt đến giới hạn số PANEL,  do đó không thể cài buộc" },
    "製品 NG 狀態上傳失敗，請確認網路連線！": { vn: "Sản phẩm NG trạng thái tải lên thất bại, hãy kiểm tra mạng kết nối!" },
    "製品 OK 狀態上傳失敗，請確認網路連線！": { vn: "Sản phẩm OK trạng thái tải lên thất bại, hãy kiểm tra mạng kết nối!" },
    "請等待平台退回上料區": { vn: "Chờ máy trả về khu lên liệu" },
    "作業後將達 PANEL 數上限，因此無法繼續執行。": { vn: "Sau khi làm đạt đến giới hạn số PANEL, do đó không thể tiếp tục chấp hành" },
    "請放入至少放入一個OK製品": { vn: "Hãy để vào ít nhất để 1 sản phẩm OK vào" },
    "請保持平台無任何製品": { vn: "Hãy duy trì mặt máy không có bất kỳ sản phẩm nào" },
    "工單上傳失敗，請確認網路連線！": { vn: "Công đơn đăng lên thất bại, hãy kiểm tra mạng kết nối!" },
    "作業已完成！": { vn: "Đã làm xong hoành thành!" },
    "測試模式": { vn: "Dạng thử nghiệm" },
    "品目panel數:...，是否結束?": { vn: "Số panel  mục hàng:..., có kết thúc không?" },
    "NG;已達PANEL數，無法綁定": { vn: "NG, đã đạt đế số PANEL, không thể cài buộc" },
    "跳站": { vn: "Nhảy trạm " },
    "重工": { vn: "Làm lại" },
    "建立失敗": { vn: "Thiết lập thất bại" },
    "混工單": { vn: "Lẫn công đơn" },
    "混品目": { vn: "Lẫn mục hàng" },
    "進出料製品 2DID 不同，請確認機台是否操作正常": {vn: "Nhập xuất liệu sản phẩm 2DID không giống nhau, hãy kiểm tra máy có làm đúng hay không"},
    "與後台連線中斷，已切換至本地儲存模式": {vn: "Mất kết nối với máy chủ, đã chuyển sang chế độ lưu trữ cục bộ."},
    "系統處理中...": {vn: "Xử lý hệ thống"},
    "登出": {vn: "Thoát ra"},
    "OK 請按印刷進": {vn: "OK nhấn in-xoa tiến"},
    "已印刷完成，請按印刷出": {vn: "Đã in xong, hãy nhấn in-xoa ra"},
    "印刷進": {vn: "in-xoa tiến"},
    "印刷出": {vn: "in-xoa ra"},
    "請刷入工號": {vn: "Hãy quét nhập cung-hao"},
    "請刷入工單": {vn: "Hãy quét nhập cung-tan"},
    "請刷入2DID": {vn: "Hãy quét nhập 2DID"},
    "製品印刷中...請掃下一個": {vn: "Sản phẩm đang in-xoa...hãy quét cái tiếp theo"},
    "工站": {vn: "Công đoạn (cung-tran)"},
    "與後台連線中斷，已切換至本地儲存模式": {vn: "Kết nối máy chủ bị ngắt, chuyển sang chế độ lưu trữ tại máy này"},
    "系統處理中...": {vn: "Hệ thống đang xử lý ..."},
    "正在與後台建立連線，請稍後...": {vn: "Đang kết nối với máy chủ, vui lòng chờ ...."},
}